; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-t7-v14-mini32]
platform = espressif32
board = ttgo-t7-v14-mini32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_raw = yes
build_flags = 
	-Wl,-Map=firmware.map
	-D _TASK_INLINE    
	-D _DEBUG_
	-D _TASK_OO_CALLBACKS     
	-D FIRMWARE_BIN_PATH=".pio/build/ttgo-t7-v14-mini32/firmware.bin"
	-include Arduino.h
	-DTASKSCHEDULER_USE_INLINED_GPR_EXPRESSIONS=0
	-DTASKSCHEDULER_INTERNAL_DEFS_ONLY
	-Os                   ; Optimize for size
	-ffunction-sections   ; Place each function in its own section
	-fdata-sections       ; Place each data item in its own section
	-Wl,--gc-sections     ; Remove unused code sections during linking
	-g0                   ; Disable debug information
	; Disable unused components
	-DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=1  ; Set log level to WARNING (reduced log overhead)
	-DCONFIG_ARDUINO_ISR_IRAM=0           ; Don't place ISRs in IRAM by default
	-DCONFIG_LOG_DEFAULT_LEVEL=1          ; ESP-IDF log level to WARNING
	-DCORE_DEBUG_LEVEL=1                  ; Set Core debug level to WARNING
	; Disable Bluetooth if not used
	; -DBTDM_ENABLED=0
	; -DCONFIG_BT_ENABLED=0
	; -DCONFIG_BLUEDROID_ENABLED=0
	; Minimize WiFi buffers if used
	-DCONFIG_LWIP_TCP_MSL=3600            ; Minimize TCP connection timeout
	-DCONFIG_SPIRAM_CACHE_WORKAROUND=0    ; Disable PSRAM cache workaround if not needed

board_build.partitions = min_spiffs.csv

lib_deps = 
	bblanchon/ArduinoJson@^7.3.1
	knolleary/PubSubClient@^2.8
	wifwaf/MH-Z19@^1.5.4
	fu-hsi/PMS Library@^1.1.0
	arkhipenko/TaskScheduler@^3.7.0
	plerup/EspSoftwareSerial@^8.1.0
	tzapu/WiFiManager@2.0.17
	sensirion/Sensirion I2C SHT4x@^1.1.2
	Adafruit/Adafruit Unified Sensor@^1.1.9
	Adafruit/DHT sensor library@^1.4.4
	https://github.com/jcomas/S8_UART.git

; Custom scripts for size analysis
; extra_scripts = 
;     pre:analyze_size.py
    ; post:sign_firmware.py	

; Custom script for analyzing firmware size
; Create this file in your project root 